[package]
name = "crypto-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
age = { version = "0.9.1", features = ["web-sys"] }
getrandom = { version = "0.2.9", features = ["js"] }
wasm-bindgen = "0.2"
